# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 바이칼AI 기술 블로그
email: master@baikal.ai
description: > # this means to ignore newlines until "baseurl:"
  바이칼 기술 블로그는 바이칼AI 기술 및 연구개발 과정에서 얻어진 다양한 내용을
  공유합니다. 인공지능, 딥러닝, 자연어 처리, SW 공학, 품질 등 다양한 주제를 다룹니다.
baseurl: "/blog"
#baseurl: "/"
url: "/" # the base hostname & protocol for your site
author: baikal.ai
# twitter_username: jekyllrb
github_username: baikalai
# gitlab_username:  pages

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
